export const templateData = [
    {
        name: "YouTube Premium",
        version: "1.0",
        price: "220",
        account_type: "Tài Khoản Cấp - Không Dùng Chung",
        duration: "12 Tháng",
        payment_status: "Thanh toán sau khi add dịch vụ",
        features: ["Mỗi khách 1 tài khoản, không dùng chung", "Tài khoản được tra cứu, khách có thể login và có thể dự..."],
        warranty: "Bảo hành theo thời gian gói hiệu lực",
        promotion: "",
        is_popular: true,
    },
    {
        name: "YouTube Premium",
        version: "1.1",
        price: "250",
        account_type: "Chính Chủ - Add vào Family/ Teams",
        duration: "6 tháng",
        payment_status: "Thanh toán sau khi add dịch vụ",
        features: ["Nâng cấp từ tài khoản chính chủ", "Dùng đủ từ 3 - 5 thiết bị"],
        warranty: "Bảo hành theo thời gian gói hiệu lực",
        promotion: "",
        is_popular: false,
    },
    {
        name: "YouTube Premium",
        version: "1.1",
        price: "420",
        account_type: "Chính Chủ - Add vào Family/ Teams",
        duration: "12 Tháng",
        payment_status: "Thanh toán sau khi add dịch vụ",
        features: ["Nâng cấp từ tài khoản chính chủ", "Dùng song song YouTube Premium + Google One (Drive, Photo, Gmail...)"],
        warranty: "Bảo hành theo thời gian gói hiệu lực",
        promotion: "",
        is_popular: false,
    },
    {
        name: "YouTube + GG One",
        version: "1.2",
        capacity: "(100GB)",
        price: "519",
        account_type: "Chính Chủ - Add vào Family/ Teams",
        duration: "12 Tháng",
        payment_status: "Thanh toán sau khi add dịch vụ",
        features: ["Nâng cấp từ tài khoản chính chủ", "Dùng song song YouTube Premium + Google One (Drive, Photo, Gmail...)"],
        warranty: "Bảo hành theo thời gian gói hiệu lực",
        promotion: "Tăng Google Gemini Pro 6 tháng",
        is_popular: false,
    },
    {
        name: "YouTube + GG One",
        version: "1.2",
        capacity: "(200GB)",
        price: "550",
        account_type: "Chính Chủ - Add vào Family/ Teams",
        duration: "12 Tháng",
        payment_status: "Thanh toán sau khi add dịch vụ",
        features: ["Nâng cấp từ tài khoản chính chủ", "Dùng song song YouTube Premium + Google One (Drive, Photo, Gmail...)"],
        warranty: "Bảo hành theo thời gian gói hiệu lực",
        promotion: "Tăng Google Gemini Pro 6 tháng",
        is_popular: false,
    },
    {
        name: "YouTube + GG One",
        version: "1.2",
        capacity: "(400GB)",
        price: "599",
        account_type: "Chính Chủ - Add vào Family/ Teams",
        duration: "12 Tháng",
        payment_status: "Thanh toán sau khi add dịch vụ",
        features: ["Nâng cấp từ tài khoản chính chủ", "Dùng song song YouTube Premium + Google One (Drive, Photo, Gmail...)"],
        warranty: "Bảo hành theo thời gian gói hiệu lực",
        promotion: "Tăng Google Gemini Pro 6 tháng",
        is_popular: false,
    },
]
